export const TRANSACTION_CONSTANTS = {
  MIN_AMOUNT: 0.01,
  MAX_AMOUNT: 999999999.99,
  MAX_CONCEPT_LENGTH: 500,
} as const;

export const USER_CONSTANTS = {
  MAX_USERNAME_LENGTH: 32,
  MAX_NAME_LENGTH: 64,
} as const;

export const GROUP_CONSTANTS = {
  MAX_TITLE_LENGTH: 256,
  MAX_DESCRIPTION_LENGTH: 1000,
  DEFAULT_BALANCE: 0,
} as const;

export const ORGANIZATION_CONSTANTS = {
  MAX_NAME_LENGTH: 100,
  DEFAULT_MAX_GROUPS: 5,
  DEFAULT_MAX_USERS: 10,
  DEFAULT_MAX_TRANSACTIONS: 1000,
  DEFAULT_TIMEZONE: 'America/Mexico_City',
  DEFAULT_CURRENCY: 'MXN',
  DEFAULT_LOCALE: 'es-MX',
} as const;

export const TELEGRAM_CONSTANTS = {
  MAX_MESSAGE_LENGTH: 4096,
  MAX_CALLBACK_DATA_LENGTH: 64,
  RATE_LIMIT_WINDOW_MS: 60000,
  RATE_LIMIT_MAX_REQUESTS: 30,
} as const;
